### PR TITLE
RSpec Test

### PR DESCRIPTION
**Pull request by oxenprogrammer**
## Rspec Test
- This PR performs unit tests on relevant tic-tac-toe classes

## Libraries Used
- Rspec for the actual test
- SimpleCov for code coverage

## Setup
- `bundle install` to install the gem

## Testing
- Run `rspec` at the root of the project in the terminal
- On windows run `open coverage/index.html` for code coverage
- On unix based systems run `xdg-open coverage/index.html` for code coverage

### CODE REVIEW

**Review by GzimAsani — CHANGES_REQUESTED** [review]
## CHANGES REQUIRED  :stop_sign: 
### HELLO  **TEAM**  very nice project and you did a good job implementing the project requirements +1:  nice work :+1:, however you have to make the following change before I can accept:
- [x] Tests/Rspec is failing, kindly fix this issue

<hr>
### if you have any question kindly reach me on slack @GzimAsani

### HAPPY CODING :computer:

**Comment by ixboy** [comment]
Hello @GzimAsani  thank you so much for the review, we have fixed the linter errors but we are unable to submit for another review would you please help us solve this issue ?.

thank you.

**Comment by GzimAsani** [comment]
Hello  @ixboy  Can you contact me on slack @GzimAsani, I can't find you

**Comment by ixboy** [comment]
> Hello @ixboy Can you contact me on slack @GzimAsani, I can't find you

I have sent you a message on slack as well, please look at it whenever you get time. Thanks a lot.

**Review by rindrajosia — APPROVED** [review]
**Approved** 
Great job you've done on this project, congratulations! You can now merge and submit.

- [x] Before merging, add `bundle install` in your readme file. It will install all the necessary Gem.

Good luck with the next projects and happy coding.
Rindra Josia

**Pull request merged**
